theme: jekyll-theme-slate
baseurl: "/Ip-Model"
url: "https://rakesht2499.github.io"
rss: true                                                   
email_address: type@example.com
linkedin: https://www.linkedin.com/in/FirstLast
stack_exchange: https://stackexchangecom/users/0000/first-last
stack_overflow: https://stackoverflow.com/users/0000/first-last
youtube: UCqECaJ8Gagnn7YCbPEzWH6g  # Youtube token of your channel in the url 
